### ISSUE TITLE
Prepare the YAML configuration files for Symfony 3

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony-demo#246]
I'm trying to make this demo app work with Symfony 3. Right now it's impossible because KnpPaginatorBundle is not compatible with 3. However, I managed to make it work somehow and I'm seeing these deprecation errors:

```
The file "app/config/services.yml" does not contain valid YAML.

The reserved indicator "@" cannot start a plain scalar; you need to
quote the scalar at line 16 (near "arguments: [@markdown, %app_locales%]").
```

In `services.yml` we need to wrap with quotes any string that starts with `@` or `%`. If you want to submit a pull request to solve this issue, please use single quotes instead of double quotes. Thanks!

**Comment by javiereguiluz** [comment]
The same errors happen in `src/CodeExplorerBundle/DependencyInjection/../Resources/config/services.yml` file.

**Comment by javiereguiluz** [comment]
And the same errors happen in `app/config/routing.yml`

**Comment by stof** [comment]
using single quotes is easier than double quotes IMO: double quotes in Yaml require to escape many chars in the string, while single quotes only need to escape single quotes themselves (by doubling them)

**Comment by bocharsky-bw** [comment]
Useful to know, thanks!

**Comment by georgiana-gligor** [comment]
Resurrecting this one from the dead, as I fought it a little bit today.
The solution that worked in my case is based on @stof 's suggestion:
```yml
        type:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: '`type`' # << note the single quote AND backtick
```

Hope it helps someone gain time.
