### ISSUE TITLE
Application use a production database in a test environment.

### ISSUE THREAD

**Issue by voronkovich** [symfony/symfony-demo#556]
https://github.com/symfony/symfony-demo/blob/master/app/config/config.yml#L65
```yml
# config.yml
doctrine:
    dbal:
        url: "%env(DATABASE_URL)%"
```
https://github.com/symfony/symfony-demo/blob/master/app/config/config_test.yml#L24
```yml
# config_test.yml
doctrine:
    dbal:
        # It doesn't override an "url" value!
        path: "%kernel.root_dir%/../var/data/blog_test.sqlite"
```
