### ISSUE TITLE
Sort configuration entries?

### ISSUE THREAD

**Issue by garak** [symfony/symfony-demo#651]
Can we introduce a new convention? The configuration entries (I'm thinking of yaml now, but it could be used in other formats also) should be ordered _alphabetically_.
This could improve readability.
I see that this has been already done for `config/packages/framework.yaml`, but other files are inconsistent.

**Comment by javiereguiluz** [comment]
I've been thinking about this. I was the one sorting the `framework.yaml` options alphabetically ... and now I think that was a mistake. I think it's better to follow the exact same sorting provided by Flex, to avoid confusion.

We could propose to sort options in all Flex recipes ... but I think sometimes that's not desirable. For example, this is not sorted:

```yaml
App\:
    resource: '../src/*'
    exclude: '../src/{Entity,Repository,Tests}'
```

but it looks better than the sorted alternative:

```yaml
App\:
    exclude: '../src/{Entity,Repository,Tests}'
    resource: '../src/*'
```

But we can propose it and see what the community says about that.
