### ISSUE TITLE
Cannot load vendor templates

### ISSUE THREAD

**Issue by garak** [symfony/symfony-demo#652]
I'm stuck with loading vendor templates, that was automagically done in "old" Symfony apps.
For example, the menu from KnpMenu (`KnpMenuBundle::menu.html.twig`) is not loaded.

**Steps to reproduce**:
* install this app
* `composer require  knplabs/knp-menu-bundle`
* create a menu as a service, as described in bundle docs (example provided below)
* call menu from a template

**Expected**: the menu should show
**Actual**: exception `Unable to find template "KnpMenuBundle::menu.html.twig" (looked into: /home/user/symfony-demo/templates, /home/user/symfony-demo/vendor/symfony/twig-bridge/Resources/views/Form).`

**Note**: for now I added the path of vendor template in twig.yaml and of course if works, but I think this is just an ugly workaround and I expect that any vendor template should work out of the box
___
Menu class example, provided to easy reproduction:

```php
<?php
// src/Menu/Builder.php
namespace App\Menu;

use Knp\Menu\FactoryInterface;

class Builder
{
    private $factory;

    public function __construct(FactoryInterface $factory)
    {
        $this->factory = $factory;
    }

    public function createMainMenu(array $options)
    {
        $menu = $this->factory->createItem('root');
        $menu->addChild('Home', array('route' => 'homepage'));

        return $menu;
    }
}
```

added in `config/services.yaml`
```yaml
    app.menu_builder:
        class: App\Menu\Builder
        arguments: ["@knp_menu.factory"]
        public: true
        tags:
            - { name: knp_menu.menu_builder, method: createMainMenu, alias: main }

```

added in `templates/default/homepage.html.twig` (inside `body` block)

```
{{ knp_menu_render('main') }}
```
